General:
    Locale: en_US

    # Amount of time (in minutes) to wait between saves of player information
    Save_Interval: 10

    # Allow Duel to check if a new version is available
    Update_Check: true
    Prefer_Beta: false

    # Should Duel print out debug messages?
    Verbose_Logging: false

    # Should Duel over-write configs to update, or make new ones ending in .new?
    Config_Update_Overwrite: true

Duel:
    # Should Duel prevent player versus player combat outside duels?
    Prevent_PVP: false

    # Override PVP prevention from other plugins?
    Override_PVP: true

    # Save and restore a players inventory when they die in a duel?
    Save_Inventory: true

    # Duels end after 120 seconds by default in a tie
    Duel_Length: 120

    # The range in which players will receive messages about a duel starting/ending
    Message_Range: 50

    # Heal players to full health when the duel ends?
    Heal_After_Duel: true

    # Any potion effect type in this list will get removed when a duel starts
    Potion_Effects_To_Remove:
    - REGENERATION
    - INVISIBILITY

    # Players who are in a duel will not be able to use commands in this list
    Blocked_Commands:
    - /this_is_blocked

    # Actually kill players in a Duel?
    Call_DeathEvents: false

Arena:
    Knockback_Enabled: true
    Radius: 20.0

Challenge:
    # Should it be possible to challenge players to a duel using commands?
    Enable_Challenge_Commands: false

    # Should it be possible to challenge players to a duel by interacting? (RIGHT_CLICK, LEFT_CLICK, OFF)
    Challenge_Interact: RIGHT_CLICK

    # Do players have to hold shift while interacting?
    Challenge_Hold_Shift: true

    # Duel challenges expire after 30 seconds by default
    Timeout: 30

    # Items on this list can be used to challenge a player with shift + right click.
    # Adding 'Air' will allow players to send a challenge while unarmed.
    Duel_Items:
      - Diamond_Sword
      - Diamond_Axe
      - Gold_Sword
      - Gold_Axe
      - Iron_Sword
      - Iron_Axe
      - Stone_Sword
      - Stone_Axe
      - Wood_Sword
      - Wood_Axe

WorldGuard:
    # Use the region list as a whitelist?
    Use_As_Whitelist: false

    # Players can(not) duel in the regions listed below.
    Regions:
    - no_duels_here

Worlds:
    # Use the world list as a whitelist?
    Use_As_Whitelist: false

    # Players can(not) duel in the worlds listed below.
    Worlds:
    - no_duels_here
